# Generated by Django 5.2.8 on 2025-12-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detectiontrack',
            new_name='detection_t_camera__127b9b_idx',
            old_name='detection_t_camera__idx',
        ),
        migrations.RenameIndex(
            model_name='detectiontrack',
            new_name='detection_t_is_acti_d355f7_idx',
            old_name='detection_t_is_acti_idx',
        ),
    ]
