# Generated by Django 5.2.8 on 2026-04-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportquery',
            new_name='support_que_branch__7b34b9_idx',
            old_name='sq_branch_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='supportquery',
            new_name='support_que_sender__eeb9a1_idx',
            old_name='sq_sender_created_at_idx',
        ),
    ]
