# Generated by Django 5.2.8 on 2025-12-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='last_feed_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time feed was confirmed active (updated by external feed checker)', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], db_index=True, default='OFFLINE', max_length=20),
        ),
    ]
