# Generated by Django 5.2.8 on 2025-11-24 15:13

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('person_id', models.CharField(db_index=True, max_length=255)),
                ('vector', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Tracking Record',
                'verbose_name_plural': 'Tracking Records',
                'db_table': 'tracking_records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['person_id', '-timestamp'], name='tracking_re_person__c0ff9c_idx')],
            },
        ),
    ]
