# Generated by Django 5.2.8 on 2026-04-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingrecord',
            name='bbox',
            field=models.JSONField(default=list, help_text='Bounding box [x1, y1, x2, y2]'),
        ),
        migrations.AddField(
            model_name='trackingrecord',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='Detection confidence from YOLO (0-1)'),
        ),
        migrations.AddField(
            model_name='trackingrecord',
            name='global_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Cross-camera global identity ID from ReID/FAISS', null=True),
        ),
        migrations.AddField(
            model_name='trackingrecord',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Snapshot of the camera location at recording time', max_length=255),
        ),
        migrations.AddField(
            model_name='trackingrecord',
            name='x3d_score',
            field=models.FloatField(blank=True, help_text='Latest X3D theft probability at time of recording', null=True),
        ),
    ]
