# Generated by Django 5.2.8 on 2025-11-24 15:13

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceEvent',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('frame_url', models.CharField(blank=True, max_length=512)),
                ('ai_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_events', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Surveillance Event',
                'verbose_name_plural': 'Surveillance Events',
                'db_table': 'surveillance_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
