# Generated by Django 5.2.8 on 2025-12-27 14:04

import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetAudit',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('is_admin', models.BooleanField(db_index=True, default=False)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Password Reset Audit',
                'verbose_name_plural': 'Password Reset Audits',
                'db_table': 'accounts_password_reset_audit',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', '-timestamp'], name='accounts_pa_email_b9e236_idx'), models.Index(fields=['is_admin', 'success', '-timestamp'], name='accounts_pa_is_admi_138035_idx')],
            },
        ),
    ]
