# Generated by Django 5.2.8 on 2026-04-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_super_admin_and_reset_requests'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='branch',
            new_name='branches_tenant__c5ffaa_idx',
            old_name='branches_tenant_branch_name_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='branches_status_bf7330_idx',
            old_name='branches_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='branchpasswordresetrequest',
            new_name='branch_pass_status_ad0e90_idx',
            old_name='bprr_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='branchpasswordresetrequest',
            new_name='branch_pass_branch__81e9a8_idx',
            old_name='bprr_branch_created_at_idx',
        ),
    ]
